name: Sync changes from Repo A to Repo B

on:
  push:
    branches:
      - testing  # Trigger the workflow when a commit is pushed to 'testing' branch
  workflow_dispatch:  # Allow manual triggering of the workflow from the UI

env:
  REPO_B: repo-sync-test-b

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo A
      - name: Checkout repo A
        uses: actions/checkout@v3
        with:
          ref: testing  # Ensures that the 'testing' branch is checked out

      # Step 2: Clone repo B
      - name: Clone repo B
        run: |
          git clone https://${{ secrets.PAT }}@github.com/mrahman-at-speer/$REPO_B.git
          cd $REPO_B
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          cd ..
      
      # Step 3: Copy all contents of repo A to repo B, excluding .github folder
      - name: Copy repo A contents to repo B (excluding .github)
        run: |
          rsync -av --exclude='.github' --exclude='.git' ./ $REPO_B/  # Copy all files, excluding the .github folder

      # Step 6: Commit and push the changes to repo B
      - name: Commit and push the changes to repo B
        run: |
          cd $REPO_B
          git add .
          git commit -m "Sync changes from repo A to repo B"
          git push origin main
